services:
  app:
    build:
      target: dev
    environment:
      PHP_IDE_CONFIG: "serverName=fetnet"
    restart: unless-stopped
    ports:
      - "8090:8090"

  nginx:
    restart: unless-stopped

  mariadb:
    restart: unless-stopped
    ports:
      - "3310:3306"

  redis:
    restart: unless-stopped
    ports:
      - "6382:6379"
