<?php

use App\Models\FetNet\Cluster;
use App\Models\FetNet\Program;
use App\Models\FetNet\Teacher;
use Livewire\Attributes\On;
use Livewire\Component;
use Mary\Traits\Toast;

/**
 * Create/edit sheet for a Teacher. The study-program picker is offered only when the
 * program is clustered (so a lecturer can be filed under any cluster program). The 3-char
 * code is auto-generated when blank or duplicate within the cluster. Emits
 * 'teacher-changed' on save.
 */
new class extends Component
{
    use Toast;

    public bool   $modal          = false;
    public ?int   $editId         = null;
    public string $code           = '';
    public string $univ_code      = '';
    public string $employee_id    = '';
    public string $position       = '';
    public string $civil_grade    = '';
    public string $front_title    = '';
    public string $rear_title     = '';
    public string $name           = '';
    public string $email          = '';
    public string $phone          = '';
    public ?int   $studyProgramId = null;

    public array $studyProgramOptions = [];

    /** The signed-in user's program. */
    private function program(): ?Program
    {
        return Program::where('user_id', auth()->id())->first();
    }

    /** Program ids sharing this program's cluster (just its own id if unclustered). */
    private function clusterProgramIds(Program $program): array
    {
        $entry = Cluster::where('program_id', $program->id)->first();
        if (! $entry) return [$program->id];
        return Cluster::where('cluster_base_id', $entry->cluster_base_id)
            ->pluck('program_id')->toArray();
    }

    /** Load the study-program options on first render (clustered programs only). */
    public function mount(): void
    {
        $program = $this->program();
        if ($program) $this->loadStudyProgramOptions($program);
    }

    /** Populate the study-program picker (empty unless the program is in a cluster). */
    private function loadStudyProgramOptions(Program $program): void
    {
        $ids = $this->clusterProgramIds($program);
        if (count($ids) <= 1) { $this->studyProgramOptions = []; return; }
        $this->studyProgramOptions = Program::whereIn('id', $ids)->orderBy('abbrev')->get(['id', 'abbrev', 'name'])
            ->map(fn($p) => ['id' => $p->id, 'name' => "{$p->abbrev} — {$p->name}"])->toArray();
    }

    /**
     * Decide the final 3-char code: keep the requested code if valid + unused, else the
     * existing code, else auto-generate from the name. Returns [code, wasAutoGenerated].
     */
    private function resolveCode(string $requested, string $name, array $usedCodes, ?string $existingCode = null): array
    {
        $requested = strtoupper(trim($requested));
        if (strlen($requested) === 3 && ! in_array($requested, $usedCodes)) return [$requested, false];
        if ($existingCode && strlen($existingCode) === 3 && ! in_array(strtoupper($existingCode), $usedCodes)) {
            return [strtoupper($existingCode), false];
        }
        return [Teacher::generateCode($name, $usedCodes), true];
    }

    /** Open the sheet for a new teacher (defaults to this program). */
    #[On('open-teacher-create')]
    public function openCreate(): void
    {
        $this->reset(['code', 'univ_code', 'employee_id', 'position', 'civil_grade', 'front_title', 'rear_title', 'name', 'email', 'phone', 'editId']);
        $this->studyProgramId = $this->program()?->id;
        $this->modal = true;
    }

    /** Open the sheet prefilled from an existing teacher. */
    #[On('open-teacher-edit')]
    public function openEdit(int $id): void
    {
        $t                    = Teacher::findOrFail($id);
        $this->editId         = $id;
        $this->studyProgramId = $t->program_id;
        $this->code           = $t->code ?? '';
        $this->univ_code      = $t->univ_code ?? '';
        $this->employee_id    = $t->employee_id ?? '';
        $this->position       = $t->position    ?? '';
        $this->civil_grade    = $t->civil_grade ?? '';
        $this->front_title    = $t->front_title ?? '';
        $this->rear_title     = $t->rear_title ?? '';
        $this->name           = $t->name;
        $this->email          = $t->email ?? '';
        $this->phone          = $t->phone ?? '';
        $this->modal          = true;
    }

    /** Validation rules for the teacher form (code is optional, 3 alpha chars). */
    protected function rules(): array
    {
        return [
            'name'           => 'required',
            'studyProgramId' => 'required|exists:institution_program,id',
            'code'           => 'nullable|size:3|alpha',
            'univ_code'      => 'nullable|max:4',
            'employee_id'    => 'nullable',
            'position'       => 'nullable|max:100',
            'civil_grade'    => 'nullable|max:50',
            'front_title'    => 'nullable',
            'rear_title'     => 'nullable',
            'email'          => 'nullable|email',
            'phone'          => 'nullable',
        ];
    }

    /**
     * Validate, ensure the chosen program is within the cluster, resolve the 3-char code
     * (auto-generating if needed), then create/update the teacher and emit 'teacher-changed'.
     */
    public function save(): void
    {
        $this->validate();

        $program = $this->program();
        $ids     = $this->clusterProgramIds($program);

        if (! in_array($this->studyProgramId, $ids)) {
            $this->addError('studyProgramId', 'Invalid program.');
            return;
        }

        $usedCodes = Teacher::whereIn('program_id', $ids)
            ->when($this->editId, fn($q) => $q->where('id', '!=', $this->editId))
            ->whereNotNull('code')->pluck('code')->map(fn($c) => strtoupper($c))->toArray();

        $existing     = $this->editId ? Teacher::find($this->editId) : null;
        [$code, $autoGen] = $this->resolveCode($this->code, $this->name, $usedCodes, $existing?->code);

        $data = [
            'program_id'  => $this->studyProgramId,
            'code'        => $code,
            'univ_code'   => strtoupper(trim($this->univ_code)) ?: null,
            'employee_id' => $this->employee_id ?: null,
            'position'    => $this->position    ?: null,
            'civil_grade' => $this->civil_grade ?: null,
            'front_title' => $this->front_title ?: null,
            'rear_title'  => $this->rear_title  ?: null,
            'name'        => $this->name,
            'email'       => $this->email       ?: null,
            'phone'       => $this->phone       ?: null,
        ];

        if ($this->editId) {
            Teacher::findOrFail($this->editId)->update($data);
            $this->success('Teacher updated.' . ($autoGen ? " Code auto-generated: {$code}." : ''), position: 'toast-top toast-center');
        } else {
            Teacher::create($data);
            $this->success('Teacher added.' . ($autoGen ? " Code auto-generated: {$code}." : ''), position: 'toast-top toast-center');
        }

        $this->modal = false;
        $this->dispatch('teacher-changed');
    }
}; ?>

<div>
    <x-modal wire:model="modal" :title="$editId ? 'Edit Teacher' : 'Add Teacher'"
             separator class="modal-bottom" box-class="!max-w-xl mx-auto !rounded-t-2xl !mb-14">
        <x-form wire:submit="save" class="space-y-4">
            <input type="text" class="w-0 h-0 opacity-0 absolute pointer-events-none" autofocus />
            @if(count($studyProgramOptions))
                <div class="w-3/4">
                    <x-choices label="Study Program" single searchable wire:model="studyProgramId"
                               :options="$studyProgramOptions" placeholder="-- Select Program --" required />
                </div>
            @endif
            <x-input label="Full Name" wire:model="name" placeholder="Ahmad Fauzan" required />
            <div class="grid grid-cols-5 gap-3">
                <div class="col-span-2"><x-input label="Front Title" wire:model="front_title" placeholder="Dr." /></div>
                <div class="col-span-3"><x-input label="Rear Title" wire:model="rear_title" placeholder="M.T., Ph.D." /></div>
            </div>
            <div class="grid grid-cols-4 gap-3">
                <x-input label="Code" wire:model="code" placeholder="AFK" />
                <x-input label="Univ Code" wire:model="univ_code" placeholder="A001" />
                <div class="col-span-2">
                    <x-input label="Employee ID (NIP/NIDN)" wire:model="employee_id" placeholder="19800101 200901 1 001" />
                </div>
            </div>
            <div class="grid grid-cols-[1fr_auto] gap-3">
                <x-input label="Position (Jabatan)" wire:model.live="position" placeholder="e.g. Lektor Kepala" />
                <x-input label="Civil Grade (Golongan)" wire:model.live="civil_grade" placeholder="e.g. IV/a" class="w-48" />
            </div>
            <div class="grid grid-cols-2 gap-3">
                <x-input label="Email" wire:model="email" type="email" placeholder="lecturer@univ.ac.id" />
                <x-input label="Phone" wire:model="phone" placeholder="08123456789" />
            </div>
            <x-slot:actions>
                <x-button label="Cancel" icon="o-x-circle"     wire:click="$set('modal', false)" />
                <x-button label="Save"   icon="o-check-circle" type="submit" class="btn-primary" spinner="save" />
            </x-slot:actions>
        </x-form>
    </x-modal>
</div>
