<?php

namespace App\Services\FetNet;

use App\Models\FetNet\ActivityTag;
use App\Models\FetNet\ActivityTimeConstraint;
use App\Models\FetNet\Building;
use App\Models\FetNet\Client;
use App\Models\FetNet\ClientConfig;
use App\Models\FetNet\Program;
use App\Models\FetNet\Semester;
use App\Models\FetNet\Student;
use App\Models\FetNet\StudentConstraint;
use App\Models\FetNet\StudentTimeConstraint;
use App\Models\FetNet\Subject;
use App\Models\FetNet\Teacher;
use App\Models\FetNet\TeacherConstraint;
use App\Models\FetNet\TeacherTimeConstraint;
use App\Models\FetNet\ActivityPlanning;
use App\Models\FetNet\Activity;
use App\Models\FetNet\TimetableSlot;
use Illuminate\Support\Collection;
use XMLWriter;

/**
 * Build a FET (Free Timetabling Software) XML file for one Client + Semester.
 *
 * Output conforms to FET v7.0+ schema. See:
 *   FetNet/docs/superpowers/specs/2026-05-15-fet-compile-design.md
 */
class FetXmlBuilder
{
    private const FET_VERSION = '7.0.8';

    private XMLWriter $w;

    /** Mon..Sun lookup, FET stores Name = English short day. */
    private array $dayNames = [];

    /** Hour-name lookup by 1-based slot index. */
    private array $hourNames = [];

    /** Maps internal Teacher.id => FET teacher Name (= code or fallback). */
    private array $teacherKey = [];

    /** Maps Subject.id => FET subject Name (= code). */
    private array $subjectKey = [];

    /** Maps Student.id => FET student-set Name (= unique label). */
    private array $studentKey = [];

    /** Maps ActivityTag.id => FET tag Name. */
    private array $tagKey = [];

    /** Maps Space.id => FET room Name (= code or fallback). */
    private array $roomKey = [];

    /** Maps Building.id => FET building Name. */
    private array $buildingKey = [];

    /** Maps DB Activity.id => array of emitted FET Activity Ids (sequential counter). */
    private array $activityIdMap = [];

    /** Returns the emit-id map produced by the last build() call. */
    public function getActivityIdMap(): array
    {
        return $this->activityIdMap;
    }

    public function build(Client $client, Semester $semester): string
    {
        $this->activityIdMap = [];
        $this->w = new XMLWriter();
        $this->w->openMemory();
        $this->w->setIndent(true);
        $this->w->setIndentString("\t");
        $this->w->startDocument('1.0', 'UTF-8');

        $this->w->startElement('fet');
        $this->w->writeAttribute('version', self::FET_VERSION);

        $this->w->writeElement('Mode', 'Official');
        $this->w->writeElement('Institution_Name', (string) $client->name);
        $this->w->writeElement('Comments', 'Generated by FetNet on ' . now()->toIso8601String());

        $config = $client->config ?? ClientConfig::where('client_id', $client->id)->first();

        $this->emitDays($config);
        $this->emitHours($config);

        $programs = Program::where('client_id', $client->id)->orderBy('abbrev')->get();
        $programIds = $programs->pluck('id');

        $subjects   = Subject::whereIn('program_id', $programIds)->orderBy('code')->get();
        $teachers   = Teacher::whereIn('program_id', $programIds)->orderBy('name')->get();
        $tags       = ActivityTag::whereIn('program_id', $programIds)->orderBy('name')->get();
        $buildings  = Building::where('client_id', $client->id)->orderBy('name')->get();
        $spaces     = \App\Models\FetNet\Space::where('client_id', $client->id)
                        ->with('building:id,name')->orderBy('name')->get();
        $students   = Student::whereIn('program_id', $programIds)
                        ->whereNull('parent_id')
                        ->with(['children.children'])
                        ->orderBy('name')->get();

        $plannings = ActivityPlanning::whereIn('program_id', $programIds)
                        ->where('semester_id', $semester->id)
                        ->pluck('id');
        $activities = Activity::whereIn('planning_id', $plannings)
                        ->with([
                            'planning.subject:id,code,name',
                            'subActivities',
                            'teachers:id,code,name',
                            'students:id,name,number_of_student',
                            'tags:id,name',
                            'spaces:id,code,name,capacity,building_id',
                            'type:id,name',
                        ])
                        ->get();

        $this->validateActivities($activities);

        $this->emitSubjects($subjects);
        $this->emitActivityTags($tags);
        $this->emitTeachers($teachers, $subjects);
        $this->emitStudents($programs, $students);
        $this->emitIndependentGroups();
        $this->emitActivities($activities, $programs);
        $this->emitBuildings($buildings);
        $this->emitRooms($spaces);

        $lockedSlots = TimetableSlot::where('client_id', $client->id)
            ->where('semester_id', $semester->id)
            ->where('locked', true)
            ->get();

        $this->emitTimeConstraints($teachers, $students, $activities, $programIds, $config, $lockedSlots);
        $this->emitSpaceConstraints($activities, $spaces, $programIds, $lockedSlots);

        $this->w->startElement('Timetable_Generation_Options_List');
        $this->w->endElement();

        $this->w->endElement(); // </fet>
        $this->w->endDocument();

        return $this->w->outputMemory();
    }

    // ─── Validation ──────────────────────────────────────────────────────

    private function validateActivities(Collection $activities): void
    {
        $items = [];

        foreach ($activities as $a) {
            $issues = [];
            if ($a->teachers->isEmpty()) $issues[] = 'No teacher assigned';
            if ($a->students->isEmpty()) $issues[] = 'No student group assigned';
            if ($a->spaces->isEmpty())   $issues[] = 'No room assigned';

            if ($issues) {
                $items[] = [
                    'id'     => $a->id,
                    'code'   => $a->planning?->subject?->code ?? '?',
                    'name'   => $a->planning?->subject?->name ?? '?',
                    'issues' => $issues,
                ];
            }
        }

        if (empty($items)) return;

        throw new \RuntimeException(json_encode([
            'type'  => 'incomplete_activities',
            'count' => count($items),
            'items' => $items,
        ], JSON_UNESCAPED_UNICODE));
    }

    // ─── Days/Hours ───────────────────────────────────────────────────────

    private function emitDays(?ClientConfig $config): void
    {
        $labels = $config?->dayLabels() ?: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'];
        $full   = [
            'Mon' => 'Monday', 'Tue' => 'Tuesday', 'Wed' => 'Wednesday',
            'Thu' => 'Thursday', 'Fri' => 'Friday', 'Sat' => 'Saturday', 'Sun' => 'Sunday',
        ];

        $this->w->startElement('Days_List');
        $this->w->writeElement('Number_of_Days', (string) count($labels));

        foreach ($labels as $i => $short) {
            $name = $full[$short] ?? $short;
            $this->dayNames[$i + 1] = $name;
            $this->w->startElement('Day');
            $this->w->writeElement('Name', $name);
            $this->w->writeElement('Long_Name', '');
            $this->w->endElement();
        }
        $this->w->endElement();
    }

    private function emitHours(?ClientConfig $config): void
    {
        $slots = $config?->generateSlots() ?: [];
        // Filter break entries: FET treats every slot as bookable; breaks become Not_Available.
        $bookable = array_values(array_filter($slots, fn($s) => ! $s['break']));

        // Fallback if config empty.
        if (empty($bookable)) {
            for ($i = 1; $i <= 8; $i++) {
                $bookable[] = ['idx' => $i, 'time' => sprintf('%02d:00', 7 + $i - 1)];
            }
        }

        $this->w->startElement('Hours_List');
        $this->w->writeElement('Number_of_Hours', (string) count($bookable));
        foreach ($bookable as $i => $slot) {
            $name = explode('–', $slot['time'])[0] ?? sprintf('%02d:00', 7 + $i);
            $this->hourNames[$i + 1] = $name;
            $this->w->startElement('Hour');
            $this->w->writeElement('Name', $name);
            $this->w->writeElement('Long_Name', '');
            $this->w->endElement();
        }
        $this->w->endElement();
    }

    // ─── Subjects ─────────────────────────────────────────────────────────

    private function emitSubjects(Collection $subjects): void
    {
        $this->w->startElement('Subjects_List');

        $seen = [];
        foreach ($subjects as $s) {
            $key = $this->uniqueLabel($s->code ?: $s->name, $seen);
            $this->subjectKey[$s->id] = $key;

            $this->w->startElement('Subject');
            $this->w->writeElement('Name', $key);
            $this->w->writeElement('Long_Name', (string) $s->name);
            $this->w->writeElement('Code', (string) ($s->code ?? ''));
            $this->w->writeElement('Comments', '');
            $this->w->endElement();
        }
        $this->w->endElement();
    }

    // ─── Activity tags ────────────────────────────────────────────────────

    private function emitActivityTags(Collection $tags): void
    {
        $this->w->startElement('Activity_Tags_List');
        $seen = [];
        foreach ($tags as $t) {
            $key = $this->uniqueLabel($t->name, $seen);
            $this->tagKey[$t->id] = $key;

            $this->w->startElement('Activity_Tag');
            $this->w->writeElement('Name', $key);
            $this->w->writeElement('Long_Name', '');
            $this->w->writeElement('Code', '');
            $this->w->writeElement('Printable', 'true');
            $this->w->writeElement('Comments', '');
            $this->w->endElement();
        }
        $this->w->endElement();
    }

    // ─── Teachers ─────────────────────────────────────────────────────────

    private function emitTeachers(Collection $teachers, Collection $subjects): void
    {
        $this->w->startElement('Teachers_List');
        $seen = [];
        // Build a teacher_id => qualified subject codes map (heuristic: subjects of same program).
        $subjectByProgram = $subjects->groupBy('program_id');

        foreach ($teachers as $t) {
            $base = $t->code ?: ($t->employee_id ?: $t->name);
            $key  = $this->uniqueLabel($base, $seen);
            $this->teacherKey[$t->id] = $key;

            $this->w->startElement('Teacher');
            $this->w->writeElement('Name', $key);
            $this->w->writeElement('Long_Name', (string) $t->full_name);
            $this->w->writeElement('Code', (string) ($t->code ?? ''));
            $this->w->writeElement('Target_Number_of_Hours', '0');

            $qualified = $subjectByProgram->get($t->program_id, collect());
            $this->w->startElement('Qualified_Subjects');
            foreach ($qualified as $s) {
                if (isset($this->subjectKey[$s->id])) {
                    $this->w->writeElement('Qualified_Subject', $this->subjectKey[$s->id]);
                }
            }
            $this->w->endElement();

            $this->w->writeElement('Comments', '');
            $this->w->endElement();
        }
        $this->w->endElement();
    }

    // ─── Students (Year → Group → Subgroup) ───────────────────────────────

    private function emitStudents(Collection $programs, Collection $rootStudents): void
    {
        $this->w->startElement('Students_List');
        $seen = [];

        // Group roots by program for namespacing.
        $rootsByProgram = $rootStudents->groupBy('program_id');
        $programByid    = $programs->keyBy('id');

        foreach ($rootsByProgram as $programId => $roots) {
            $programAbbrev = $programByid->get($programId)?->abbrev ?? "P{$programId}";
            foreach ($roots as $year) {
                $yearName = $this->uniqueLabel($programAbbrev . ' ' . $year->name, $seen);
                $this->studentKey[$year->id] = $yearName;

                $this->w->startElement('Year');
                $this->w->writeElement('Name', $yearName);
                $this->w->writeElement('Long_Name', '');
                $this->w->writeElement('Code', '');
                $this->w->writeElement('Number_of_Students', (string) ($year->number_of_student ?: 0));
                $this->w->writeElement('Comments', '');
                $this->w->writeElement('Number_of_Categories', '0');
                $this->w->writeElement('First_Category_Is_Permanent', 'false');
                $this->w->writeElement('Separator', ' ');

                foreach ($year->children as $group) {
                    $groupName = $this->uniqueLabel($yearName . ' ' . $group->name, $seen);
                    $this->studentKey[$group->id] = $groupName;

                    $this->w->startElement('Group');
                    $this->w->writeElement('Name', $groupName);
                    $this->w->writeElement('Long_Name', '');
                    $this->w->writeElement('Code', '');
                    $this->w->writeElement('Number_of_Students', (string) ($group->number_of_student ?: 0));
                    $this->w->writeElement('Comments', '');

                    foreach ($group->children as $subgroup) {
                        $subgroupName = $this->uniqueLabel($groupName . ' ' . $subgroup->name, $seen);
                        $this->studentKey[$subgroup->id] = $subgroupName;

                        $this->w->startElement('Subgroup');
                        $this->w->writeElement('Name', $subgroupName);
                        $this->w->writeElement('Long_Name', '');
                        $this->w->writeElement('Code', '');
                        $this->w->writeElement('Number_of_Students', (string) ($subgroup->number_of_student ?: 0));
                        $this->w->writeElement('Comments', '');
                        $this->w->endElement();
                    }
                    $this->w->endElement();
                }
                $this->w->endElement();
            }
        }
        $this->w->endElement();
    }

    // ─── Activities ───────────────────────────────────────────────────────

    private function emitActivities(Collection $activities, Collection $programs): void
    {
        $this->w->startElement('Activities_List');

        $counter = 1;
        foreach ($activities as $a) {
            $subject  = $a->planning?->subject;
            if (! $subject || ! isset($this->subjectKey[$subject->id])) continue;

            $teacherNames = $a->teachers->pluck('id')->map(fn($id) => $this->teacherKey[$id] ?? null)->filter()->values();
            $studentNames = $a->students->pluck('id')->map(fn($id) => $this->studentKey[$id] ?? null)->filter()->values();
            $tagNames     = $a->tags->pluck('id')->map(fn($id) => $this->tagKey[$id] ?? null)->filter()->values();

            // FET requires at least one teacher per activity — skip unassigned ones.
            if ($teacherNames->isEmpty()) continue;

            $subs       = $a->subActivities;
            $isSplit    = $subs->count() > 1;
            $components = $isSplit
                ? $subs->map(fn($s) => $s->duration)->toArray()
                : [(int) $a->duration];

            $groupId = $isSplit ? $counter : 0;
            $totalDuration = array_sum($components);

            $emittedIds = [];
            foreach ($components as $partDuration) {
                $this->w->startElement('Activity');
                $this->w->writeElement('Id', (string) $counter);
                foreach ($teacherNames as $tn) {
                    $this->w->writeElement('Teacher', $tn);
                }
                $this->w->writeElement('Subject', $this->subjectKey[$subject->id]);
                foreach ($tagNames as $tn) {
                    $this->w->writeElement('Activity_Tag', $tn);
                }
                foreach ($studentNames as $sn) {
                    $this->w->writeElement('Students', $sn);
                }
                $this->w->writeElement('Active', 'true');
                $this->w->writeElement('Total_Duration', (string) $totalDuration);
                $this->w->writeElement('Duration', (string) $partDuration);
                $this->w->writeElement('Activity_Group_Id', (string) $groupId);
                $this->w->writeElement('Comments', '');
                $this->w->endElement();
                $emittedIds[] = $counter;
                $counter++;
            }
            $this->activityIdMap[$a->id] = $emittedIds;
        }
        $this->w->endElement();
    }

    // ─── Buildings / Rooms ────────────────────────────────────────────────

    private function emitBuildings(Collection $buildings): void
    {
        $this->w->startElement('Buildings_List');
        $seen = [];
        foreach ($buildings as $b) {
            $key = $this->uniqueLabel($b->code ?: $b->name, $seen);
            $this->buildingKey[$b->id] = $key;

            $this->w->startElement('Building');
            $this->w->writeElement('Name', $key);
            $this->w->writeElement('Comments', (string) $b->name);
            $this->w->endElement();
        }
        $this->w->endElement();
    }

    private function emitRooms(Collection $spaces): void
    {
        $this->w->startElement('Rooms_List');
        $seen = [];
        foreach ($spaces as $sp) {
            $key = $this->uniqueLabel($sp->code ?: $sp->name, $seen);
            $this->roomKey[$sp->id] = $key;

            $this->w->startElement('Room');
            $this->w->writeElement('Name', $key);
            $this->w->writeElement('Long_Name', (string) $sp->name);
            $this->w->writeElement('Code', (string) ($sp->code ?? ''));
            $this->w->writeElement('Building',
                ($sp->building_id && isset($this->buildingKey[$sp->building_id]))
                    ? $this->buildingKey[$sp->building_id] : '');
            $this->w->writeElement('Capacity', (string) ($sp->capacity ?: 30));
            $this->w->writeElement('Comments', '');
            $this->w->endElement();
        }
        $this->w->endElement();
    }

    // ─── Time constraints ─────────────────────────────────────────────────

    private function emitTimeConstraints(
        Collection $teachers,
        Collection $students,
        Collection $activities,
        Collection $programIds,
        ?ClientConfig $config,
        Collection $lockedSlots
    ): void {
        $this->w->startElement('Time_Constraints_List');

        // Mandatory: basic compulsory time
        $this->w->startElement('ConstraintBasicCompulsoryTime');
        $this->w->writeElement('Weight_Percentage', '100');
        $this->w->writeElement('Active', 'true');
        $this->w->writeElement('Comments', '');
        $this->w->endElement();

        // Teacher not-available times
        $ttc = TeacherTimeConstraint::whereIn('teacher_id', $teachers->pluck('id'))->get();
        foreach ($ttc->groupBy('teacher_id') as $teacherId => $rows) {
            $key = $this->teacherKey[$teacherId] ?? null;
            if (! $key) continue;
            $valid = $rows->filter(fn($r) => isset($this->dayNames[$r->day], $this->hourNames[$r->hour]));
            if ($valid->isEmpty()) continue;
            $this->w->startElement('ConstraintTeacherNotAvailableTimes');
            $this->w->writeElement('Weight_Percentage', '100');
            $this->w->writeElement('Teacher', $key);
            $this->w->writeElement('Number_of_Not_Available_Times', (string) $valid->count());
            foreach ($valid as $r) {
                $this->w->startElement('Not_Available_Time');
                $this->w->writeElement('Day', $this->dayNames[$r->day]);
                $this->w->writeElement('Hour', $this->hourNames[$r->hour]);
                $this->w->endElement();
            }
            $this->w->writeElement('Active', 'true');
            $this->w->writeElement('Comments', '');
            $this->w->endElement();
        }

        // Student set not-available times (flatten any Student id in tree)
        $allStudentIds = $this->collectStudentIds($students);
        $stc = StudentTimeConstraint::whereIn('student_id', $allStudentIds)->get();
        foreach ($stc->groupBy('student_id') as $studentId => $rows) {
            $key = $this->studentKey[$studentId] ?? null;
            if (! $key) continue;
            $valid = $rows->filter(fn($r) => isset($this->dayNames[$r->day], $this->hourNames[$r->hour]));
            if ($valid->isEmpty()) continue;
            $this->w->startElement('ConstraintStudentsSetNotAvailableTimes');
            $this->w->writeElement('Weight_Percentage', '100');
            $this->w->writeElement('Students', $key);
            $this->w->writeElement('Number_of_Not_Available_Times', (string) $valid->count());
            foreach ($valid as $r) {
                $this->w->startElement('Not_Available_Time');
                $this->w->writeElement('Day', $this->dayNames[$r->day]);
                $this->w->writeElement('Hour', $this->hourNames[$r->hour]);
                $this->w->endElement();
            }
            $this->w->writeElement('Active', 'true');
            $this->w->writeElement('Comments', '');
            $this->w->endElement();
        }

        // Activity preferred-time slots — emit once per emitted activity instance.
        $atc = ActivityTimeConstraint::whereIn('activity_id', $activities->pluck('id'))->get();
        foreach ($atc->groupBy('activity_id') as $activityId => $rows) {
            $valid = $rows->filter(fn($r) => isset($this->dayNames[$r->day], $this->hourNames[$r->hour]));
            if ($valid->isEmpty()) continue;
            foreach ($this->activityIdMap[$activityId] ?? [] as $emitId) {
                $this->w->startElement('ConstraintActivityPreferredTimeSlots');
                $this->w->writeElement('Weight_Percentage', '100');
                $this->w->writeElement('Activity_Id', (string) $emitId);
                $this->w->writeElement('Number_of_Preferred_Time_Slots', (string) $valid->count());
                foreach ($valid as $r) {
                    $this->w->startElement('Preferred_Time_Slot');
                    $this->w->writeElement('Preferred_Day', $this->dayNames[$r->day]);
                    $this->w->writeElement('Preferred_Hour', $this->hourNames[$r->hour]);
                    $this->w->endElement();
                }
                $this->w->writeElement('Active', 'true');
                $this->w->writeElement('Comments', '');
                $this->w->endElement();
            }
        }

        // Locked starting-time from fetnet_timetable_slot. Honors per-activity locks
        // produced by the FET solver or manually edited via the lock-edit UI.
        // Maps slot row -> ConstraintActivityPreferredStartingTime with Permanently_Locked=true.
        foreach ($lockedSlots as $slot) {
            if ($slot->day_index === null || $slot->hour_index === null) continue;
            $dayName  = $this->dayNames[$slot->day_index] ?? null;
            $hourName = $this->hourNames[$slot->hour_index] ?? null;
            if (! $dayName || ! $hourName) continue;
            foreach ($this->activityIdMap[$slot->activity_id] ?? [] as $emitId) {
                $this->w->startElement('ConstraintActivityPreferredStartingTime');
                $this->w->writeElement('Weight_Percentage', '100');
                $this->w->writeElement('Activity_Id', (string) $emitId);
                $this->w->writeElement('Preferred_Day', $dayName);
                $this->w->writeElement('Preferred_Hour', $hourName);
                $this->w->writeElement('Permanently_Locked', 'true');
                $this->w->writeElement('Active', 'true');
                $this->w->writeElement('Comments', '');
                $this->w->endElement();
            }
        }

        // Numeric teacher constraints (max_days_per_week, max_gaps_per_week, etc.)
        $tNumeric = TeacherConstraint::whereIn('program_id', $programIds)->get();
        foreach ($tNumeric as $c) {
            $this->emitTeacherNumericConstraint($c);
        }

        $sNumeric = StudentConstraint::whereIn('program_id', $programIds)->get();
        foreach ($sNumeric as $c) {
            $this->emitStudentNumericConstraint($c);
        }

        $this->w->endElement();
    }

    private function emitTeacherNumericConstraint(TeacherConstraint $c): void
    {
        $teacherKey = $c->teacher_id ? ($this->teacherKey[$c->teacher_id] ?? null) : null;

        $map = [
            'max_days_per_week'              => 'ConstraintTeacherMaxDaysPerWeek',
            'min_days_per_week'              => 'ConstraintTeacherMinDaysPerWeek',
            'max_hours_continuously'         => 'ConstraintTeacherMaxHoursContinuously',
            'max_hours_daily'                => 'ConstraintTeacherMaxHoursDaily',
            'max_gaps_per_week'              => 'ConstraintTeacherMaxGapsPerWeek',
            'max_gaps_per_day'               => 'ConstraintTeacherMaxGapsPerDay',
        ];

        $tag = $map[$c->constraint_type] ?? null;
        if (! $tag) return;
        if (! $teacherKey) return;

        $this->w->startElement($tag);
        $this->w->writeElement('Weight_Percentage', (string) ($c->weight ?? 100));
        if (str_contains($tag, 'MaxDays'))   $this->w->writeElement('Max_Days_Per_Week', (string) $c->value);
        if (str_contains($tag, 'MinDays'))   $this->w->writeElement('Min_Days_Per_Week', (string) $c->value);
        if (str_contains($tag, 'Continuously')) $this->w->writeElement('Maximum_Hours_Continuously', (string) $c->value);
        if (str_contains($tag, 'HoursDaily'))   $this->w->writeElement('Maximum_Hours_Daily', (string) $c->value);
        if (str_contains($tag, 'GapsPerWeek'))  $this->w->writeElement('Max_Gaps', (string) $c->value);
        if (str_contains($tag, 'GapsPerDay'))   $this->w->writeElement('Max_Gaps', (string) $c->value);
        $this->w->writeElement('Teacher', $teacherKey);
        $this->w->writeElement('Active', 'true');
        $this->w->writeElement('Comments', '');
        $this->w->endElement();
    }

    private function emitStudentNumericConstraint(StudentConstraint $c): void
    {
        $studentKey = $c->student_id ? ($this->studentKey[$c->student_id] ?? null) : null;
        if (! $studentKey) return;

        $map = [
            'max_hours_continuously' => 'ConstraintStudentsSetMaxHoursContinuously',
            'max_hours_daily'        => 'ConstraintStudentsSetMaxHoursDaily',
            'max_gaps_per_week'      => 'ConstraintStudentsSetMaxGapsPerWeek',
            'max_gaps_per_day'       => 'ConstraintStudentsSetMaxGapsPerDay',
        ];
        $tag = $map[$c->constraint_type] ?? null;
        if (! $tag) return;

        $this->w->startElement($tag);
        $this->w->writeElement('Weight_Percentage', (string) ($c->weight ?? 100));
        if (str_contains($tag, 'Continuously')) $this->w->writeElement('Maximum_Hours_Continuously', (string) $c->value);
        if (str_contains($tag, 'HoursDaily'))   $this->w->writeElement('Maximum_Hours_Daily', (string) $c->value);
        if (str_contains($tag, 'Gaps'))         $this->w->writeElement('Max_Gaps', (string) $c->value);
        $this->w->writeElement('Students', $studentKey);
        $this->w->writeElement('Active', 'true');
        $this->w->writeElement('Comments', '');
        $this->w->endElement();
    }

    // ─── Space constraints ────────────────────────────────────────────────

    private function emitSpaceConstraints(Collection $activities, Collection $spaces, Collection $programIds, Collection $lockedSlots): void
    {
        $this->w->startElement('Space_Constraints_List');

        $this->w->startElement('ConstraintBasicCompulsorySpace');
        $this->w->writeElement('Weight_Percentage', '100');
        $this->w->writeElement('Active', 'true');
        $this->w->writeElement('Comments', '');
        $this->w->endElement();

        $lockedRoomByActivity = $lockedSlots->filter(fn($s) => $s->room_id)
            ->keyBy('activity_id');

        // Activity preferred rooms (from assignment pivot).
        // Skip activities whose room is already locked via fetnet_timetable_slot — emitted below.
        foreach ($activities as $a) {
            if ($lockedRoomByActivity->has($a->id)) continue;
            $rooms = $a->spaces;
            if ($rooms->isEmpty()) continue;

            // Prefer rooms that fit the student count; if none do, fall back to
            // all assigned rooms so FET still has concrete guidance (rather than
            // searching the full room list and potentially finding nothing).
            $totalStudents = (int) $a->students->sum('number_of_student');
            $fitting = $totalStudents > 0
                ? $rooms->filter(fn($sp) => (int) ($sp->capacity ?? 0) >= $totalStudents)
                : $rooms;
            $emitRooms = $fitting->isNotEmpty() ? $fitting : $rooms;

            foreach ($this->activityIdMap[$a->id] ?? [] as $emitId) {
                if ($emitRooms->count() === 1) {
                    $sp = $emitRooms->first();
                    if (! isset($this->roomKey[$sp->id])) continue;
                    $this->w->startElement('ConstraintActivityPreferredRoom');
                    $this->w->writeElement('Weight_Percentage', '100');
                    $this->w->writeElement('Activity_Id', (string) $emitId);
                    $this->w->writeElement('Room', $this->roomKey[$sp->id]);
                    $this->w->writeElement('Permanently_Locked', 'false');
                    $this->w->writeElement('Active', 'true');
                    $this->w->writeElement('Comments', '');
                    $this->w->endElement();
                } else {
                    $this->w->startElement('ConstraintActivityPreferredRooms');
                    $this->w->writeElement('Weight_Percentage', '100');
                    $this->w->writeElement('Activity_Id', (string) $emitId);
                    $this->w->writeElement('Number_of_Preferred_Rooms', (string) $emitRooms->count());
                    foreach ($emitRooms as $sp) {
                        if (isset($this->roomKey[$sp->id])) {
                            $this->w->writeElement('Preferred_Room', $this->roomKey[$sp->id]);
                        }
                    }
                    $this->w->writeElement('Active', 'true');
                    $this->w->writeElement('Comments', '');
                    $this->w->endElement();
                }
            }
        }

        // Locked rooms from fetnet_timetable_slot.
        foreach ($lockedRoomByActivity as $activityId => $slot) {
            $roomKey = $this->roomKey[$slot->room_id] ?? null;
            if (! $roomKey) continue;
            foreach ($this->activityIdMap[$activityId] ?? [] as $emitId) {
                $this->w->startElement('ConstraintActivityPreferredRoom');
                $this->w->writeElement('Weight_Percentage', '100');
                $this->w->writeElement('Activity_Id', (string) $emitId);
                $this->w->writeElement('Room', $roomKey);
                $this->w->writeElement('Permanently_Locked', 'true');
                $this->w->writeElement('Active', 'true');
                $this->w->writeElement('Comments', '');
                $this->w->endElement();
            }
        }

        $this->w->endElement();
    }

    // ─── Independent groups (FET 7.0+) ───────────────────────────────────

    private function emitIndependentGroups(): void
    {
        $this->w->startElement('Independent_Groups_List');
        $this->w->endElement();
    }

    // ─── Helpers ──────────────────────────────────────────────────────────

    private function uniqueLabel(string $base, array &$seen): string
    {
        $base = trim($base) ?: 'Unnamed';
        $candidate = $base;
        $i = 2;
        while (isset($seen[$candidate])) {
            $candidate = $base . '_' . $i++;
        }
        $seen[$candidate] = true;
        return $candidate;
    }

    private function collectStudentIds(Collection $rootStudents): array
    {
        $ids = [];
        $walk = function ($node) use (&$walk, &$ids) {
            $ids[] = $node->id;
            foreach ($node->children ?? [] as $c) $walk($c);
        };
        foreach ($rootStudents as $r) $walk($r);
        return $ids;
    }
}
